// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppGSL.h>
#include <Rcpp.h>

using namespace Rcpp;

// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP GSLtools_rcpp_hello_world() {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        List __result = rcpp_hello_world();
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// matinterp
NumericMatrix matinterp(NumericVector x, NumericMatrix Y, NumericMatrix Xi);
RcppExport SEXP GSLtools_matinterp(SEXP xSEXP, SEXP YSEXP, SEXP XiSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        NumericVector x = Rcpp::as<NumericVector >(xSEXP);
        NumericMatrix Y = Rcpp::as<NumericMatrix >(YSEXP);
        NumericMatrix Xi = Rcpp::as<NumericMatrix >(XiSEXP);
        NumericMatrix __result = matinterp(x, Y, Xi);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
