# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('GSLtools_rcpp_hello_world', PACKAGE = 'GSLtools')
}

#' Matrix Linear Interpolator
#'
#' takes 2 matrices Y and Xi, and a grid x. x and Y are
#' original function values on x and Xi are new points
#' at which to evaluate the function. Linear Interpolation.
#' @param x grid on which Y=f(x) defined
#' @param Y matrix of funciton values. each row is a different function defined on same grid.
#' @param Xi matrix of new grid values at which to obtain Xi = f(Yi).
#' @examples
#' x <- seq(0,1,le=10)
#' Y <- log(outer(1:5,x,"+"))
#' Xi <- matrix(seq(0.1,0.99,le=12),5,12,byrow=T)
#' res <- matinterp(x,Y,Xi)
matinterp <- function(x, Y, Xi) {
    .Call('GSLtools_matinterp', PACKAGE = 'GSLtools', x, Y, Xi)
}

